FORMAT = 'utf-8'

UNITY_BUFFER_SIZE = 1
UNITY_PORT = 5000
UNITY_IP = 'localhost'
UNITY_REQUEST = '1'
UNITY_DISCONNECT = '0'

EEG_PORT = 8080
EEG_IP = ''
EEG_GET_DATA_MSG = bytes('1', encoding='utf-8')
EEG_DISCONNECT_MSG = bytes('0', encoding='utf-8')
EEG_BUFFER_SIZE = 20000
EEG_SAMPLING_RATE = 1024
EEG_SAMPLING_NUM = 512
EEG_ELECTRODE_NUM = 64

PATH = '..\..\Events.csv'
