# [FORMAT]
FORMAT = 'utf-8'

# [UNITY]
UNITY_BUFFER_SIZE = 512
UNITY_PORT = 5001
UNITY_IP = '127.0.0.1'
UNITY_REQUEST = '1'
UNITY_DISCONNECT = '0'
UNITY_MESSAGE_TIMEOUT = 2
UNITY_CLIENT_TIMEOUT = 30

# [EEG] (can also have GSR or others)
EEG_PORT = 5002
EEG_IP = '127.0.0.1'  # '192.168.1.20'
EEG_GET_DATA_MSG = '1'
EEG_DISCONNECT_MSG = '0'
EEG_BUFFER_SIZE = 20000
EEG_SAMPLING_RATE = 1
EEG_SAMPLING_NUM = 16
EEG_ELECTRODE_NUM = 64
EEG_MAX_FREQ = 70
EEG_CLIENT_TIMEOUT = 2

# [PATH] (to events)
PATH = 'Events.csv'

# [MANAGER] (manager information)
DECISION_LOOP_TIME = 2
DECISION_MAKER = 'easy'
PROCESSOR = 'raw_data'

